FROM ubuntu:latest

EXPOSE 3000

RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    wget \
    curl \
    unzip

#Installer npm 8.19.3 et Nodejs 10.13.0
RUN curl -fsSL https://nodejs.org/dist/v18.13.0/node-v18.13.0-linux-x64.tar.xz | tar -xJf - -C /usr/local --strip-components=1
RUN npm install -g npm@8.19.4

WORKDIR /app

COPY maestro-app ./maestro-app

RUN npm --prefix maestro-app/ install

CMD ["npm", "start", "--prefix", "maestro-app"]
