name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        distribution: 'oracle'
        java-version: '22'

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget curl unzip flatpak
        pip install --upgrade pip
        pip install music21

    - name: Install Gradle
      run: |
        wget https://services.gradle.org/distributions/gradle-8.8-bin.zip
        unzip gradle-8.8-bin.zip
        mv gradle-8.8 /opt/gradle
        echo "export PATH=\$PATH:/opt/gradle/bin" >> $GITHUB_ENV

    - name: Build with Gradle
      run: gradle clean build -x test

    - name: Run Java Tests
      run: gradle test
